Zhenya/communication
OfficeDev/fluent-react-patterns pull request #18
Opened 2021-10-27 06:39 UTC by zhenyasav

2021-10-29 23:01 UTC, thure requested changes

2021-10-29 23:01 UTC, thure commented on src/lib/FluentKitProvider.tsx
>  export const FluentKitProvider = ({
All good, same feedback about renaming `FluentKit…` to maybe `FluentPatterns…` or something.

2021-10-29 23:07 UTC, thure commented on .storybook/preview.js
> +    document.body.classList.toggle('debug-css')
Although… depending on what you’re debugging, there may be a solid Storybook addon for it! What are you using this for?

2021-10-29 23:08 UTC, thure commented on src/blocks/Centered/Centered.tsx
> +    margin: '20px',
Or, lib needs a new function for incrementing spacings (`margin`, `padding`, `gap` at least) by .25rem and the rest of this project should use that.

2021-10-30 07:15 UTC, zhenyasav commented on src/lib/FluentKitContext.ts
> +}
yes but it should also just be merged with fluent components, or somehow be the exact same provider `<FluentProvider>` or honestly just `<Fluent> { your stuff } </Fluent>`

2021-10-30 07:15 UTC, zhenyasav commented on .storybook/preview.js
> +    document.body.classList.toggle('debug-css')
i just like seeing at a glance how the dom is laid out when i'm building without having to mouse over elements in the dev tools

2021-10-30 07:16 UTC, zhenyasav commented on src/blocks/Illustration/models.ts
> +import { z } from 'zod'
idk that was just my instinct, it doesn't matter really, let's pick a word you like

2021-10-30 07:17 UTC, zhenyasav commented on src/lib/propsElementUnion.ts
> +}
your second type argument i found to be unnecessary because it's always `z.infer<Z>`

2021-10-30 08:04 UTC, zhenyasav commented
ok @thure actions are ready for another look, we have to finish deciding about how to do event handling

2021-11-01 19:14 UTC, thure commented on src/lib/propsElementUnion.ts
> +}
Oh I see. We should refactor all of them to use the new implementation of this, then. Guess that can come in another PR though.

2021-11-01 20:30 UTC, thure requested changes
Just a few smaller asks this time! This is coming along nicely ✨

2021-11-01 20:30 UTC, thure commented on src/blocks/Communication/Communication.tsx
> +function escaped<T extends ZodTypeAny>(arg: T) {
If this should become a common pattern, it should move to lib rather than being internal to this component.

2021-11-01 20:30 UTC, thure commented on src/blocks/Illustration/ThemedImage.tsx
> +      {typeof value == 'string' ? <img src={value} /> : value}
All `img` tags need an `alt` to meet a11y standards.

2021-11-01 20:30 UTC, thure commented on src/blocks/Illustration/ThemedImage.tsx
> +      {typeof value == 'string' ? <img src={value} /> : value}
> Setting this attribute to an empty string (alt="") indicates that this image is not a key part of the content (it’s decoration or a tracking pixel), and that non-visual browsers may omit it from rendering. Visual browsers will also hide the broken image icon if the alt is empty and the image failed to display.

I think it'd be fair to give this `alt=""`.

2021-11-01 20:30 UTC, thure commented on src/blocks/Illustration/ThemedImage.tsx
> +    height: '200px',
`rem` s.v.p. ✨

2021-11-01 20:30 UTC, thure commented on src/blocks/Illustration/ThemedImage.tsx
> +    '& > *': {
Is the splat selector still verboten? I forget… tbf I don't mind it, just checking.

2021-11-01 20:30 UTC, thure commented on src/blocks/Illustration/ThemedImage.tsx
> +    '& > *': {
I'm not seeing anything conclusive about this, so resolving this.

2021-11-01 21:02 UTC, zhenyasav commented on src/blocks/Illustration/ThemedImage.tsx
> +    '& > *': {
star selector? or & selector? is that really called a splat? afaik splat is `...` within `{ ... spreads }` ?

2021-11-02 00:21 UTC, thure commented on src/blocks/Illustration/models.ts
> +import { z } from 'zod'
I like ‘models’! Very suitable 👌

2021-11-02 00:23 UTC, thure commented on src/blocks/Illustration/ThemedImage.tsx
> +    '& > *': {
Interesting, I haven’t heard that one. My mentor always called the asterisk 'splat': http://catb.org/jargon/html/A/ASCII.html

2021-11-13 01:55 UTC, thure approved these changes
Merged in fixes which brings this into mergeability.

2021-11-13 01:58 UTC, merged