BigMessage implementation adjustments
OfficeDev/fluent-react-patterns pull request #20
Opened 2021-11-10 02:00 UTC by thure

2021-11-11 23:20 UTC, zhenyasav requested changes
love to see a PR with most of the bulk in tests, awesome - thank you!

2021-11-11 23:20 UTC, zhenyasav commented on src/blocks/Heading/index.ts
> -export * from './Heading'
you prefer `import { Heading } from 'blocks/Heading/Heading'` over `import { Heading } from 'blocks/Heading'` ?

2021-11-11 23:20 UTC, zhenyasav commented on src/blocks/Section/Section.test.tsx
> +              <Escape contentMeetsAccessibilityAndDesignStandards key="t1">
I thought we auto-issue keys based on referential equality? are you optimizing for the fact that this will always be a new instance/reference and therefore will always get a new key?

2021-11-11 23:20 UTC, zhenyasav commented on src/inlines/Icon/Icon.test.tsx
> +    before(async function (this) {
i would avoid naming parameters `this` maybe? it's strictly speaking fine to do this, but it's an unexpected pattern for me, and in general it feels like nails on a blackboard when we're hiding the real `this` value like that ... if I didnt look at the parameter signature (which i didn't at first) and just saw a line of code that starts with `this....` that implies the real `this` but this isn't the real `this` and that seemed like an unnecessary mental burden...

2021-11-11 23:20 UTC, zhenyasav commented on src/inlines/Icon/Icon.test.tsx
> +    before(async function (this) {
just ranting feel free to ignore if you feel strongly about this (pun intended)

2021-11-11 23:20 UTC, zhenyasav commented on src/inlines/Inline/Inline.test.tsx
> +          <Inline {...{ potato: 'squirrel' }} />
moot point but doesnt it feel wrong to malloc just to set one property? `<Inline potato="squirrel" />` ?

2021-11-11 23:20 UTC, zhenyasav commented on src/inlines/Inline/Inline.test.tsx
> +          await this.page
now every time i see `this` i get extra anxious looking at whether it's the real `this` or a parameter hiding the real `this` .... not pleasant

2021-11-11 23:20 UTC, zhenyasav commented on src/inputs/Button/Button.test-stories.tsx
> +  <FluentPatternsProvider onAction={onAction}>
does `<View />` get the same privilege of handling actions? we should discuss state container in more detail

2021-11-11 23:20 UTC, zhenyasav commented on src/inputs/Button/Button.tsx
> +export const Button = ({
i was hoping to avoid wrapping button with button but perhaps i can see we're adding some value here, let's discuss

2021-11-11 23:20 UTC, zhenyasav commented on src/lib/Illustration/Illustration.stories.mdx
> +<Meta title="Facets/Illustrations" component={Illustration} />
whats the definition of `facet` and how does it differ from `block` ?

2021-11-11 23:20 UTC, zhenyasav commented on src/lib/actions.tsx
> +export type PropsWithActionHandler<P> = P & { onAction?: ActionHandler }
hiding the second type argument to `ActionHandler`? `PropsWithActionHandler<P,A = ActionPayload> = ... `?

2021-11-11 23:27 UTC, thure commented on src/blocks/BigMessage/BigMessage.tsx
> +function ActionsBlock({ primary, secondary, tertiary }: ActionsBlockProps) {
This is an interesting question… I suppose groups of buttons can be considered a design pattern, but if we treat it as such, then we should properly classify and expose the component.

You could argue it is a kind of `input`, and I would agree with that. Maybe there is a vertical variation for this component, and a horizontal one for dialogs like for "Okay | Cancel" etc, since AFAIK that also has the concept of 'primary', 'secondary', 'tertiary'.

2021-11-11 23:28 UTC, thure commented on src/blocks/BigMessage/BigMessage.stories.mdx
> +          primary: { actionId: 'a1', label: 'Sign in' },
`actionId` is for the developer to identify an interactive element at the global scope, at least that is what I've proposed, and there is no guarantee that e.g. a primary button here would be the only primary button in the View.

2021-11-11 23:29 UTC, thure commented on src/blocks/Heading/index.ts
> -export * from './Heading'
Not necessarily, I deleted it for now because I think I'd prefer to get consistency all at once rather than incrementally in an architectural matter like this. I do like the idea.

2021-11-11 23:30 UTC, thure commented on src/inlines/Inline/Inline.test.tsx
> +          await this.page
That's Mocha for you ¯\_(ツ)_/¯… I don't think there's a satisfying workaround.

2021-11-11 23:31 UTC, thure commented on src/inputs/Button/Button.test-stories.tsx
> +  <FluentPatternsProvider onAction={onAction}>
Oh, that's an interesting question, I hadn't thought of that…

Maybe our first-class patterns like View will take an `onAction` handler and pass that to their Provider since IIRC they would all render one themselves.

2021-11-11 23:33 UTC, thure commented on src/inputs/Button/Button.tsx
> +export const Button = ({
There are some lower-level components like this where I think this will happen, where we mainly offer our higher-level API and more Opinionated™ usage of a lower-level component from `react-components`. Part of wrapping this is to take care of dispatching the correct action payload.

2021-11-11 23:38 UTC, thure commented on src/lib/Illustration/Illustration.stories.mdx
> +<Meta title="Facets/Illustrations" component={Illustration} />
I created the idea of 'facet' to describe a feature of this library that isn't expressly a component in our ontology.

The idea of a 'block' is it is a component that naturally occupies the full inline axis and flows along the block axis.

That said, as I'm looking closer at the `Illustration` component as you have it, I'm seeing it is exactly that. I'll fix this.

2021-11-11 23:39 UTC, thure commented on src/lib/actions.tsx
> +export type PropsWithActionHandler<P> = P & { onAction?: ActionHandler }
Ah, good catch! Thank you.

2021-11-11 23:44 UTC, thure commented on src/blocks/BigMessage/BigMessage.tsx
> +  title: inlineSequence,
If you give a moose a muffin…

I think on the surface this isn't a bad idea, though in these early stages I was thinking of reserving `string` in these places for some unanticipated purpose.

I agree for un-formatted plain text, `{text: 'potato'}` feels too verbose, but I don't think the place to make that change is in this PR.

2021-11-11 23:44 UTC, thure commented on src/blocks/BigMessage/BigMessage.tsx
> +  title: inlineSequence,
Also, `inlineSequence` is already escaped:

```tsx
export const inlineEntity = z.union([
  textPropsOrElement,
  iconPropsOrElement,
  escapeElement,
])
export type InlineEntity = z.infer<typeof inlineEntity>

export const inlineSequence = z.array(inlineEntity)
export type InlineSequence = z.infer<typeof inlineSequence>
```

2021-11-12 00:21 UTC, thure commented on src/lib/Illustration/Illustration.stories.mdx
> +<Meta title="Facets/Illustrations" component={Illustration} />
Hm… as I'm fleshing out `Illustration` to be a full block, it's feeling more and more like it's actually a kind of figure, perhaps? It's essentially captioned by the text below it…

2021-11-12 01:30 UTC, thure commented on src/inlines/Icon/Icon.test.tsx
> +    before(async function (this) {
todo: remove `this` when it's not typed

2021-11-13 01:50 UTC, thure commented on src/blocks/BigMessage/BigMessage.tsx
> +function ActionsBlock({ primary, secondary, tertiary }: ActionsBlockProps) {
I decided `ActionsBlock` is a specific kind of `ShortInputs`, so I created a variation for it.

2021-11-13 01:52 UTC, merged